//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Carts = new HashSet<Cart>();
            this.CouponCustomers = new HashSet<CouponCustomer>();
            this.CouponRefers = new HashSet<CouponRefer>();
            this.CouponRefers1 = new HashSet<CouponRefer>();
            this.MembersPointHistories = new HashSet<MembersPointHistory>();
            this.Notifications = new HashSet<Notification>();
            this.Orders = new HashSet<Order>();
            this.ReceiveAddresses = new HashSet<ReceiveAddress>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Code { get; set; }
        public string Token { get; set; }
        public System.DateTime DOB { get; set; }
        public string Email { get; set; }
        public int Role { get; set; }
        public int Sex { get; set; }
        public string AvatarUrl { get; set; }
        public Nullable<int> ProvinceCode { get; set; }
        public Nullable<int> DistrictCode { get; set; }
        public Nullable<int> WardID { get; set; }
        public string Address { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public int Status { get; set; }
        public System.DateTime ExpireTocken { get; set; }
        public int Type { get; set; }
        public System.DateTime CraeteDate { get; set; }
        public int IsActive { get; set; }
        public string DeviceID { get; set; }
        public string Password { get; set; }
        public string PasswordReset { get; set; }
        public double Point { get; set; }
        public Nullable<int> RankID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> ExpPasswordReset { get; set; }
        public Nullable<int> OTP { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CouponCustomer> CouponCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CouponRefer> CouponRefers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CouponRefer> CouponRefers1 { get; set; }
        public virtual District District { get; set; }
        public virtual Province Province { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MembersPointHistory> MembersPointHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual Ranking Ranking { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiveAddress> ReceiveAddresses { get; set; }
    }
}
