//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MrFishEntities : DbContext
    {
        public MrFishEntities()
            : base("name=MrFishEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<CategoryNew> CategoryNews { get; set; }
        public virtual DbSet<Config> Configs { get; set; }
        public virtual DbSet<Coupon> Coupons { get; set; }
        public virtual DbSet<CouponCustomer> CouponCustomers { get; set; }
        public virtual DbSet<CouponRanking> CouponRankings { get; set; }
        public virtual DbSet<CouponRefer> CouponRefers { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<GroupItem> GroupItems { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemsSale> ItemsSales { get; set; }
        public virtual DbSet<MembersPointHistory> MembersPointHistories { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<OrderHistory> OrderHistories { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Ranking> Rankings { get; set; }
        public virtual DbSet<ReceiveAddress> ReceiveAddresses { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Ward> Wards { get; set; }
    }
}
