//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public int ItemID { get; set; }
        public int QTY { get; set; }
        public Nullable<int> ItemSaleID { get; set; }
        public Nullable<int> QTYSale { get; set; }
        public long SumPrice { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int IsActive { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual ItemsSale ItemsSale { get; set; }
        public virtual Order Order { get; set; }
    }
}
