//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHistory
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public string Title { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual User User { get; set; }
    }
}
